// <auto-generated />
namespace BoomsaFitnessBL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Eating1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Eating1));
        
        string IMigrationMetadata.Id
        {
            get { return "202109151024261_Eating1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
